import { Link } from "wouter";
import { useTranslation } from "react-i18next";
import { ClientPortalSection, formatClientDate } from "@/components/client/ClientPortalPage";
import { ServiceAgreementStatusBadge } from "@/components/ui/ServiceAgreementStatusBadge";

export function ClientRequestStatus({ status }: { status: string }) {
  const { t } = useTranslation();
  const emphasis = ["declined"].includes(status) ? "bg-red-50 text-red-700" : ["proposal_available", "agreement_available"].includes(status) ? "bg-amber-50 text-amber-800" : "bg-primary-50 text-primary-800";
  return <span className={`badge max-w-full whitespace-normal ${emphasis}`}>{t(`clientRequests.statuses.${status}`)}</span>;
}

export function ClientRequestCard({ request }: { request: any }) {
  const { t } = useTranslation();
  return <Link href={`/client/requests/${request._id}`} className="touch-target block rounded-xl border border-gray-200 bg-white p-4 shadow-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2"><article className="grid min-w-0 gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><h2 className="break-words font-semibold text-gray-900">{request.requestedService || t("clientRequests.serviceRequest")}</h2><p className="mt-1 break-words text-sm text-gray-600">{request.locationName || request.locationAddress || t("clientHome.notSet")}</p><p className="mt-1 break-words text-sm text-gray-500">{request.providerName}</p><p className="mt-2 text-xs text-gray-500">{t("clientRequests.submittedOn", { date: formatClientDate(request.submittedAt, "") })}</p></div><div className="sm:text-right"><ClientRequestStatus status={request.status} /><p className="mt-2 text-sm text-gray-700">{t("clientRequests.preferredDateValue", { date: formatClientDate(request.requestedDate, t("clientHome.notSet")) })}</p><p className="text-sm text-gray-500">{t(`clientRequests.timeWindows.${request.timeWindow}`, { defaultValue: request.timeWindow })}</p>{request.actionRequired && <p className="mt-2 text-sm font-medium text-amber-700">{t("clientRequests.actionRequired")}</p>}</div></article></Link>;
}

export function ClientRequestsPresentation({ data }: { data: any }) {
  const { t } = useTranslation();
  return data.requests.length === 0 ? <ClientPortalSection title={t("clientRequests.title")} empty={t("clientRequests.empty")} count={0}><span /></ClientPortalSection> : <div className="grid gap-3">{data.requests.map((request: any) => <ClientRequestCard key={request._id} request={request} />)}</div>;
}

export function ClientRequestDetailPresentation({ request }: { request: any }) {
  const { t } = useTranslation();
  return <div className="space-y-4"><section className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words text-xl font-semibold text-gray-900">{request.requestedService || t("clientRequests.serviceRequest")}</h2><p className="mt-1 break-words text-sm text-gray-500">{request.providerName}</p></div><ClientRequestStatus status={request.status} /></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Detail label={t("clientRequests.location")} value={[request.locationName, request.locationAddress].filter(Boolean).join(" · ")} /><Detail label={t("clientRequests.submitted")} value={formatClientDate(request.submittedAt, "")} /><Detail label={t("clientRequests.preferredDate")} value={formatClientDate(request.requestedDate, t("clientHome.notSet"))} /><Detail label={t("clientRequests.preferredTime")} value={t(`clientRequests.timeWindows.${request.timeWindow}`, { defaultValue: request.timeWindow })} /></dl>{request.notes && <div className="mt-5"><h3 className="text-sm font-medium text-gray-700">{t("clientRequests.notes")}</h3><p className="mt-1 whitespace-pre-wrap break-words text-sm text-gray-600">{request.notes}</p></div>}</section>{request.requestedAddOns.length > 0 && <ClientPortalSection title={t("clientRequests.addOns")} empty="" count={request.requestedAddOns.length}><ul className="space-y-2">{request.requestedAddOns.map((item: any) => <li key={item.sourceCompanyAddOnId} className="break-words text-sm text-gray-700">{item.name}{item.quantity ? ` × ${item.quantity}` : ""}</li>)}</ul></ClientPortalSection>}{request.scheduledService && <ClientPortalSection title={t("clientRequests.confirmedService")} empty="" count={1}><p className="text-sm text-gray-700">{formatClientDate(request.scheduledService.scheduledDate, "")} · {request.scheduledService.startTime || t("clientHome.timeToBeConfirmed")}</p></ClientPortalSection>}{request.proposals.length > 0 && <ClientPortalSection title={t("clientHome.proposals")} empty="" count={request.proposals.length}><div className="space-y-2">{request.proposals.map((item: any) => <p key={item._id} className="text-sm text-gray-700">{item.title} · {t(`clientPresentation.statuses.${item.status}`, { defaultValue: item.status })}</p>)}</div></ClientPortalSection>}{request.agreements.length > 0 && <ClientPortalSection title={t("clientHome.serviceAgreements")} empty="" count={request.agreements.length}><div className="space-y-2">{request.agreements.map((item: any) => <Link key={item._id} href={`/client/service-agreements/${item._id}`} className="touch-target flex flex-wrap items-center justify-between gap-2 rounded-lg border border-gray-200 p-3 focus:outline-none focus:ring-2 focus:ring-primary-500"><span className="break-words text-sm font-medium text-gray-900">{item.title}</span><ServiceAgreementStatusBadge agreement={item} audience="client" /></Link>)}</div></ClientPortalSection>}</div>;
}

function Detail({ label, value }: { label: string; value?: string }) { return <div><dt className="text-xs font-medium text-gray-500">{label}</dt><dd className="mt-1 break-words text-sm text-gray-900">{value || "—"}</dd></div>; }
