import { beforeEach, describe, expect, it } from "vitest";
import { convexTest } from "convex-test";
import schema from "../../schema";
import { api } from "../../_generated/api";
import { hashPassword } from "../password";

const modules = import.meta.glob("../../**/*.ts"); const PASSWORD = "test-password-123";
async function setup() {
  const t = convexTest(schema, modules); const passwordHash = await hashPassword(PASSWORD);
  const ids = await t.run(async ctx => {
    const company = await ctx.db.insert("companies", { name: "Clean Co", timezone: "America/New_York" }); const otherCompany = await ctx.db.insert("companies", { name: "Other", timezone: "UTC" });
    const owner = await ctx.db.insert("users", { email: "owner@schedule.test", passwordHash, name: "Owner", companyId: company, role: "owner", status: "active" });
    const manager = await ctx.db.insert("users", { email: "manager@schedule.test", passwordHash, name: "Manager", companyId: company, role: "manager", status: "active", canManageSchedule: true });
    const blockedManager = await ctx.db.insert("users", { email: "blocked@schedule.test", passwordHash, name: "Blocked", companyId: company, role: "manager", status: "active", canManageSchedule: false });
    const cleaner = await ctx.db.insert("users", { email: "cleaner@schedule.test", passwordHash, name: "Cleaner", companyId: company, role: "cleaner", status: "active" });
    const otherOwner = await ctx.db.insert("users", { email: "other@schedule.test", passwordHash, name: "Other", companyId: otherCompany, role: "owner", status: "active" });
    const client = await ctx.db.insert("clientUsers", { email: "client@schedule.test", passwordHash, displayName: "Client", status: "active", createdAt: 1, updatedAt: 1 });
    const relationship = await ctx.db.insert("clientRelationships", { companyId: company, clientUserId: client, displayName: "Client", clientType: "residential", status: "active", createdAt: 1, updatedAt: 1 });
    const property = await ctx.db.insert("properties", { companyId: company, clientRelationshipId: relationship, name: "Home", type: "residential", address: "1 Main", amenities: [], active: true });
    const account = await ctx.db.insert("commercialAccounts", { companyId: company, clientRelationshipId: relationship, clientName: "Office", serviceAddress: "2 Main", status: "active", createdAt: 1, updatedAt: 1 });
    const request = await ctx.db.insert("clientRequests", { companyId: company, clientRelationshipId: relationship, originClientUserId: client, createdAt: 2, status: "new", requesterName: "Client", requesterEmail: "client@schedule.test", propertySnapshot: { name: "Home", address: "1 Main" }, propertyId: property, requestedDate: "2027-06-15", timeWindow: "morning", requestedService: "Deep Clean", notes: "Internal-facing request notes", source: "authenticated_client" });
    const commercialRequest = await ctx.db.insert("clientRequests", { companyId: company, clientRelationshipId: relationship, originClientUserId: client, createdAt: 3, status: "contacted", requesterName: "Client", requesterEmail: "client@schedule.test", propertySnapshot: { name: "Office", address: "2 Main" }, commercialAccountId: account, requestedDate: "2027-06-16", timeWindow: "afternoon", requestedService: "Maintenance", source: "authenticated_client" });
    return { company, otherCompany, owner, manager, blockedManager, cleaner, otherOwner, client, relationship, property, account, request, commercialRequest };
  });
  const login = async (email: string) => (await t.action(api.authActions.signIn, { email, password: PASSWORD })).sessionToken;
  const clientToken = (await t.action(api.clientAuthActions.signIn, { email: "client@schedule.test", password: PASSWORD })).sessionToken;
  return { t, ...ids, ownerToken: await login("owner@schedule.test"), managerToken: await login("manager@schedule.test"), blockedToken: await login("blocked@schedule.test"), cleanerToken: await login("cleaner@schedule.test"), otherToken: await login("other@schedule.test"), clientToken, schedule: (api as any).mutations.jobs.confirmClientRequestSchedule, portal: (api as any).queries.clientPortal };
}
const args = (s: any, overrides: any = {}) => ({ userId: s.owner, sessionToken: s.ownerToken, requestId: s.request, scheduledDate: "2027-06-20", startTime: "10:30", durationMinutes: 150, type: "deep_clean", clientSchedulingNote: "We confirmed your service.", idempotencyKey: "schedule_key_123456789", ...overrides });
describe("business scheduling confirmation", () => {
  beforeEach(() => { process.env.TOKEN_PEPPER = "schedule-pepper"; process.env.STRIPE_SECRET_KEY = "test"; process.env.STRIPE_WEBHOOK_ACCOUNT_SECRET = "test"; process.env.RESEND_API_KEY = "test"; process.env.RESEND_FROM_EMAIL = "test@example.com"; process.env.APP_URL = "http://localhost:5173"; });
  it("atomically creates one linked residential job and safely replays stale attempts", async () => { const s = await setup(); const first = await s.t.mutation(s.schedule, args(s)); const replay = await s.t.mutation(s.schedule, args(s, { startTime: "11:00", idempotencyKey: "different_key_123456" })); expect(replay).toMatchObject({ jobId: first.jobId, replayed: true, startTime: "10:30" }); const state: any = await s.t.run(async ctx => ({ request: await ctx.db.get(s.request), jobs: await ctx.db.query("jobs").withIndex("by_sourceClientRequestId", q => q.eq("sourceClientRequestId", s.request)).collect() })); expect(state.jobs).toHaveLength(1); expect(state.jobs[0]).toMatchObject({ propertyId: s.property, clientRelationshipId: s.relationship, scheduledDate: "2027-06-20", clientSchedulingNote: "We confirmed your service.", status: "confirmed" }); expect(state.request).toMatchObject({ requestedDate: "2027-06-15", timeWindow: "morning", status: "converted" }); const detail = await s.t.query(s.portal.getClientRequestDetail, { clientUserId: s.client, sessionToken: s.clientToken, requestId: s.request }); expect(detail.request).toMatchObject({ status: "scheduled", notes: "Internal-facing request notes", scheduledService: { _id: first.jobId, clientSchedulingNote: "We confirmed your service." } }); });
  it("allows schedule-enabled managers, supports commercial locations, and denies other roles", async () => { const s = await setup(); const result = await s.t.mutation(s.schedule, args(s, { userId: s.manager, sessionToken: s.managerToken, requestId: s.commercialRequest, type: "maintenance", idempotencyKey: "commercial_key_123456" })); const job: any = await s.t.run(ctx => ctx.db.get(result.jobId)); expect(job).toMatchObject({ commercialAccountId: s.account }); expect(job).not.toHaveProperty("propertyId"); await expect(s.t.mutation(s.schedule, args(s, { userId: s.blockedManager, sessionToken: s.blockedToken }))).rejects.toThrow("permission"); await expect(s.t.mutation(s.schedule, args(s, { userId: s.cleaner, sessionToken: s.cleanerToken }))).rejects.toThrow("Owner or manager"); await expect(s.t.mutation(s.schedule, args(s, { userId: s.otherOwner, sessionToken: s.otherToken }))).rejects.toThrow("Access denied"); });
  it("rejects invalid state, relationship, location, time, and note without creating a job", async () => { const s = await setup(); await s.t.run(ctx => ctx.db.patch(s.request, { status: "declined" })); await expect(s.t.mutation(s.schedule, args(s))).rejects.toThrow("current state"); await s.t.run(ctx => ctx.db.patch(s.request, { status: "new" })); for (const override of [{ scheduledDate: "2020-01-01" }, { startTime: "25:00" }, { durationMinutes: 1 }, { clientSchedulingNote: "x".repeat(501) }]) await expect(s.t.mutation(s.schedule, args(s, override))).rejects.toThrow(); expect(await s.t.run(ctx => ctx.db.query("jobs").collect())).toHaveLength(0); await s.t.run(ctx => ctx.db.patch(s.relationship, { status: "inactive" })); await expect(s.t.mutation(s.schedule, args(s))).rejects.toThrow("relationship"); });
  it("derives scheduled, in-progress, and completed only from the linked job lifecycle", async () => { const s = await setup(); let list = await s.t.query(s.portal.listClientRequests, { clientUserId: s.client, sessionToken: s.clientToken }); expect(list.requests.find((item: any) => item._id === s.request).status).toBe("submitted"); const result = await s.t.mutation(s.schedule, args(s)); list = await s.t.query(s.portal.listClientRequests, { clientUserId: s.client, sessionToken: s.clientToken }); expect(list.requests.find((item: any) => item._id === s.request).status).toBe("scheduled"); await s.t.run(ctx => ctx.db.patch(result.jobId, { status: "in_progress" })); list = await s.t.query(s.portal.listClientRequests, { clientUserId: s.client, sessionToken: s.clientToken }); expect(list.requests.find((item: any) => item._id === s.request).status).toBe("in_progress"); await s.t.run(ctx => ctx.db.patch(result.jobId, { status: "approved", completedAt: Date.now() })); list = await s.t.query(s.portal.listClientRequests, { clientUserId: s.client, sessionToken: s.clientToken }); expect(list.requests.find((item: any) => item._id === s.request).status).toBe("completed"); });
});
