/* eslint-disable */
/**
 * Generated Convex API.
 *
 * THIS FILE IS AUTO-GENERATED by `npx convex dev`.
 * Run `npx convex dev` to regenerate.
 */

import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 */
export const api = anyApi;
export const internal = anyApi;
