/* eslint-disable */
/**
 * Generated Convex API types.
 *
 * THIS FILE IS AUTO-GENERATED by `npx convex dev`.
 * Run `npx convex dev` to regenerate.
 */

import type { ApiFromModules } from "convex/server";
import type * as auth from "../auth.js";
import type * as mutations_employees from "../mutations/employees.js";
import type * as mutations_forms from "../mutations/forms.js";
import type * as mutations_jobs from "../mutations/jobs.js";
import type * as mutations_notifications from "../mutations/notifications.js";
import type * as mutations_properties from "../mutations/properties.js";
import type * as mutations_redFlags from "../mutations/redFlags.js";
import type * as mutations_storage from "../mutations/storage.js";
import type * as queries_auditLog from "../queries/auditLog.js";
import type * as queries_dashboard from "../queries/dashboard.js";
import type * as queries_employees from "../queries/employees.js";
import type * as queries_forms from "../queries/forms.js";
import type * as queries_jobs from "../queries/jobs.js";
import type * as queries_notifications from "../queries/notifications.js";
import type * as queries_properties from "../queries/properties.js";
import type * as queries_redFlags from "../queries/redFlags.js";
import type * as queries_storage from "../queries/storage.js";

declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  "mutations/employees": typeof mutations_employees;
  "mutations/forms": typeof mutations_forms;
  "mutations/jobs": typeof mutations_jobs;
  "mutations/notifications": typeof mutations_notifications;
  "mutations/properties": typeof mutations_properties;
  "mutations/redFlags": typeof mutations_redFlags;
  "mutations/storage": typeof mutations_storage;
  "queries/auditLog": typeof queries_auditLog;
  "queries/dashboard": typeof queries_dashboard;
  "queries/employees": typeof queries_employees;
  "queries/forms": typeof queries_forms;
  "queries/jobs": typeof queries_jobs;
  "queries/notifications": typeof queries_notifications;
  "queries/properties": typeof queries_properties;
  "queries/redFlags": typeof queries_redFlags;
  "queries/storage": typeof queries_storage;
}>;

export declare const api: typeof fullApi;
export declare const internal: any;
