import { useQuery } from "convex/react";
import { useTranslation } from "react-i18next";
import { api } from "../../../../../convex/_generated/api";
import { ClientPortalPage, ClientPortalSection } from "@/components/client/ClientPortalPage";
import { LanguageSwitcher } from "@/components/shared/LanguageSwitcher";
import { useClientAuth } from "@/hooks/useClientAuth";

export function ClientAccountPresentation({ data }: { data: any }) { const { t } = useTranslation(); return <div className="grid gap-4 lg:grid-cols-2"><ClientPortalSection title={t("clientHome.contactInformation")} empty="" count={1}><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-medium text-gray-500">{t("common.name")}</dt><dd className="break-words text-sm text-gray-900">{data.clientUser.displayName}</dd></div><div><dt className="text-xs font-medium text-gray-500">{t("auth.email")}</dt><dd className="break-words text-sm text-gray-900">{data.clientUser.email}</dd></div><div><dt className="text-xs font-medium text-gray-500">{t("common.phone")}</dt><dd className="break-words text-sm text-gray-900">{data.clientUser.phone || t("clientHome.notSet")}</dd></div><div><dt className="mb-1 text-xs font-medium text-gray-500">{t("clientAccount.language")}</dt><dd><LanguageSwitcher /></dd></div></dl></ClientPortalSection><ClientPortalSection title={t("clientHome.relationships")} empty={t("clientHome.noRelationships")} count={data.relationships.length}><div className="grid gap-3">{data.relationships.map((relationship: any) => <article key={relationship._id} className="rounded-lg border border-gray-200 p-3"><h3 className="break-words font-medium text-gray-900">{relationship.companyName}</h3><p className="break-words text-sm text-gray-500">{relationship.businessName || relationship.displayName}</p></article>)}</div></ClientPortalSection></div>; }

export function ClientAccountPage() { const { t } = useTranslation(); const { clientUserId, sessionToken } = useClientAuth(); const data = useQuery((api as any).queries.clientPortal.getClientAccount, clientUserId && sessionToken ? { clientUserId, sessionToken } : "skip"); return <ClientPortalPage title={t("clientAccount.title")} description={t("clientAccount.description")} data={data}>{data && <ClientAccountPresentation data={data} />}</ClientPortalPage>; }
