import { createElement, type ReactNode } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs"; import { resolve } from "node:path";
vi.mock("react-i18next", () => ({ useTranslation: () => ({ t: (key: string, options?: any) => options?.name ? `${key}:${options.name}` : key, i18n: { language: "en", changeLanguage: vi.fn() } }) }));
vi.mock("wouter", () => ({ Link: ({ href, children, ...props }: { href: string; children: ReactNode }) => createElement("a", { href, ...props }, children) }));
import { DemoClientPage, DemoClientRequestDetailPage } from "../pages/demo/DemoClientPage";
import { getDemoPersona, shouldRenderDemoApp } from "./demoRoute";
import { buildShowcasePath, getShowcasePages } from "./showcaseRegistry";
import { showcaseBilling, showcaseRequests, showcaseServices } from "./fixtures/clientShowcaseFixtures";

describe("Client Showcase", () => {
  it("registers every production Client Portal destination and strict demo routing", () => { expect(getDemoPersona("/internal/demo/client")).toBe("client"); expect(getDemoPersona("/internal/demo/client/requests/request-scheduled")).toBe("client"); expect(getDemoPersona("/internal/demo/clientish")).toBeNull(); expect(shouldRenderDemoApp("/internal/demo/client", "true")).toBe(true); expect(getShowcasePages("client").map(page => page.relativePath)).toEqual(["/", "/services", "/requests", "/documents", "/billing", "/locations", "/account"]); });
  it("renders every Client destination with Showcase-only navigation and no placeholders", () => { for (const page of getShowcasePages("client")) { const html = renderToStaticMarkup(createElement(DemoClientPage, { page: page.relativePath, presentation: false, currentPath: buildShowcasePath("client", page.relativePath) })); expect(html).toContain("BrightSide Cleaning Co."); expect(html).not.toContain("not included in SCRUB Showcase"); const hrefs = [...html.matchAll(/href="([^"]+)"/g)].map(match => match[1]); expect(hrefs.length).toBeGreaterThan(0); expect(hrefs.every(href => href.startsWith("/internal/demo/client"))).toBe(true); } });
  it("renders submitted, scheduled, and completed requests plus the real timeline story", () => { const list = renderToStaticMarkup(createElement(DemoClientPage, { page: "/requests", presentation: true, currentPath: "/internal/demo/client/requests" })); const detail = renderToStaticMarkup(createElement(DemoClientRequestDetailPage, { requestId: "request-scheduled", presentation: true, currentPath: "/internal/demo/client/requests/request-scheduled" })); expect(list).toContain("clientRequests.statuses.submitted"); expect(list).toContain("clientRequests.statuses.scheduled"); expect(list).toContain("clientRequests.statuses.completed"); expect(detail).toContain("clientRequests.timeline.events.submitted.label"); expect(detail).toContain("clientRequests.timeline.events.scheduled.label"); expect(detail).toContain("We confirmed the earliest available morning appointment"); expect(detail).toContain('href="/internal/demo/client/services?presentation=1"'); });
  it("keeps presentation mode free of Showcase shell chrome", () => { const html = renderToStaticMarkup(createElement(DemoClientPage, { page: "/", presentation: true, currentPath: "/internal/demo/client" })); expect(html).toContain("Sarah Johnson"); expect(html).not.toContain("Fictional workspace"); expect(html).not.toContain("Showcase navigation"); });
  it("keeps deterministic cross-page BrightSide fixtures coherent", () => { expect(showcaseServices.upcoming[0]._id).toBe(showcaseRequests.find(item => item._id === "request-scheduled")?.scheduledService?._id); expect(showcaseBilling.invoices.map(item => item.status)).toEqual(["paid", "issued", "issued"]); expect(JSON.stringify({ showcaseServices, showcaseRequests, showcaseBilling })).not.toContain("Math.random"); });
  it("preserves the entry-point isolation boundary before runtime initialization", () => { const main = readFileSync(resolve(process.cwd(), "packages/frontend/src/main.tsx"), "utf8"); expect(main.indexOf("if (demoMode)")).toBeLessThan(main.indexOf("new ConvexReactClient")); expect(main.indexOf("if (demoMode)")).toBeLessThan(main.indexOf("Sentry.init")); expect(main).toContain("if (!demoMode && import.meta.env.PROD"); const demoSource = ["packages/frontend/src/pages/demo/DemoClientPage.tsx", "packages/frontend/src/demo/fixtures/clientShowcaseFixtures.ts"].map(file => readFileSync(resolve(process.cwd(), file), "utf8")).join("\n"); expect(demoSource).not.toMatch(/useQuery|useMutation|useAction|useAuth|ConvexProvider|Sentry|analytics|serviceWorker/); });
});
