import { describe, expect, it } from "vitest";
import fs from "node:fs"; import path from "node:path";
import { deriveClientRequestTimeline, getClientRequestStatusSummary } from "./clientRequestTimeline";
declare global { interface Array<T> { at(index: number): T | undefined; } }
const base = (status = "submitted", overrides: any = {}) => ({ status, providerName: "BrightSide", agreements: [], timelineFacts: { request: { status: status === "submitted" ? "new" : status === "under_review" ? "contacted" : "converted", submittedAt: 100 }, proposals: [], agreements: [], jobs: [] }, ...overrides });
const kinds = (request: any) => deriveClientRequestTimeline(request).map(event => `${event.kind}:${event.state}`);
describe("client request timeline derivation", () => {
  it("derives submitted and under-review milestones", () => { expect(kinds(base())).toEqual(["submitted:current"]); expect(kinds(base("under_review", { timelineFacts: { request: { status: "contacted", submittedAt: 100, contactedAt: 200 }, proposals: [], agreements: [], jobs: [] } }))).toEqual(["submitted:complete", "under_review:current"]); });
  it("derives proposal and agreement evidence with safe actions", () => { const proposal = base("proposal_available", { timelineFacts: { request: { status: "contacted", submittedAt: 100 }, proposals: [{ status: "sent", sentAt: 300 }], agreements: [], jobs: [] } }); expect(kinds(proposal)).toContain("proposal_available:current"); expect(getClientRequestStatusSummary(proposal).action?.href).toBe("/client/documents"); const accepted = base("processing", { timelineFacts: { request: { status: "converted", submittedAt: 100 }, proposals: [{ status: "accepted", sentAt: 300, acceptedAt: 400 }], agreements: [], jobs: [] } }); expect(kinds(accepted).at(-1)).toBe("proposal_accepted:current"); const agreement = base("agreement_available", { agreements: [{ _id: "agreement_1", status: "sent" }], timelineFacts: { request: { status: "converted", submittedAt: 100 }, proposals: [], agreements: [{ _id: "agreement_1", status: "sent", sentAt: 500 }], jobs: [] } }); expect(kinds(agreement).at(-1)).toBe("agreement_available:current"); expect(getClientRequestStatusSummary(agreement).action?.href).toBe("/client/service-agreements/agreement_1"); const signed = base("processing", { timelineFacts: { request: { status: "converted", submittedAt: 100 }, proposals: [], agreements: [{ _id: "agreement_1", status: "signed", sentAt: 500, signedAt: 600 }], jobs: [] } }); expect(kinds(signed).at(-1)).toBe("agreement_acknowledged:current"); });
  it("derives scheduled, active, and completed only from linked jobs", () => { expect(kinds(base("processing"))).not.toContain("scheduled:current"); const scheduled = base("scheduled", { timelineFacts: { request: { status: "converted", submittedAt: 100 }, proposals: [], agreements: [], jobs: [{ status: "confirmed", scheduledDate: "2027-01-01" }] } }); expect(kinds(scheduled).at(-1)).toBe("scheduled:current"); expect(deriveClientRequestTimeline(scheduled).at(-1)?.occurredAt).toBeUndefined(); expect(kinds(base("in_progress", { timelineFacts: { request: { status: "converted", submittedAt: 100 }, proposals: [], agreements: [], jobs: [{ status: "in_progress", startedAt: 700 }] } }))).toEqual(expect.arrayContaining(["scheduled:complete", "in_progress:current"])); expect(kinds(base("completed", { timelineFacts: { request: { status: "converted", submittedAt: 100 }, proposals: [], agreements: [], jobs: [{ status: "approved", completedAt: 800 }] } }))).toEqual(expect.arrayContaining(["scheduled:complete", "completed:current"])); });
  it("renders decline terminal and never invents timestamps", () => { const events = deriveClientRequestTimeline(base("declined", { timelineFacts: { request: { status: "declined", submittedAt: 100 }, proposals: [], agreements: [], jobs: [] } })); expect(events.at(-1)).toMatchObject({ kind: "declined", state: "terminal" }); expect(events.at(-1)).not.toHaveProperty("occurredAt"); });
  it("limits destinations to authenticated client routes", () => { const sample = base("scheduled", { timelineFacts: { request: { status: "converted", submittedAt: 1 }, proposals: [], agreements: [], jobs: [{ status: "confirmed" }] } }); for (const event of deriveClientRequestTimeline(sample)) if (event.destination) expect(event.destination.href).toMatch(/^\/client\//); });
});
describe("request timeline presentation contracts", () => { const root = process.cwd(); const read = (file: string) => fs.readFileSync(path.join(root, file), "utf8"); it("uses semantic responsive query-independent presentation", () => { const source = read("packages/frontend/src/components/client/ClientRequestPresentation.tsx"); expect(source).toContain("<ol"); expect(source).toContain("aria-current"); expect(source).toContain("sm:grid-cols"); expect(source).not.toContain("useQuery"); }); it("keeps English and Spanish mappings complete", () => { const en = JSON.parse(read("packages/frontend/src/i18n/en/common.json")); const es = JSON.parse(read("packages/frontend/src/i18n/es/common.json")); expect(Object.keys(en.clientRequests.timeline.events)).toEqual(Object.keys(es.clientRequests.timeline.events)); expect(Object.keys(en.clientRequests.statusSummary)).toEqual(Object.keys(es.clientRequests.statusSummary)); }); });
