import { useState } from "react";
import { Link, useParams } from "wouter";
import { useMutation, useQuery } from "convex/react";
import { api } from "../../../../../convex/_generated/api";
import { useAuth } from "@/hooks/useAuth";
import { PageHeader } from "@/components/ui/PageHeader";
import { PageLoader } from "@/components/ui/LoadingSpinner";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { RequestScheduleConfirmation } from "@/components/owner/RequestScheduleConfirmation";
import { Calendar, MapPin, Sparkles, User, XCircle } from "lucide-react";
import { useTranslation } from "react-i18next";

export function JobRequestDetailPage() {
  const { user, sessionToken } = useAuth(); const { t } = useTranslation(); const { requestId } = useParams<{ requestId: string }>();
  const request = useQuery((api as any).queries.clientRequests.getJobRequestDetail, user && sessionToken && requestId ? { userId: user._id, sessionToken, requestId } : "skip");
  const decline = useMutation((api as any).mutations.clientRequests.declineJobRequest);
  const [showDecline, setShowDecline] = useState(false); const [confirmDecline, setConfirmDecline] = useState(false); const [note, setNote] = useState(""); const [declining, setDeclining] = useState(false); const [error, setError] = useState("");
  if (request === undefined) return <PageLoader />; if (!request) return <div className="card text-center">{t("jobRequests.notFound")}</div>;
  const doDecline = async () => { setDeclining(true); setError(""); try { await decline({ userId: user!._id, sessionToken, requestId: request._id, clientFacingDecisionNote: note || undefined }); setShowDecline(false); } catch (e: any) { setError(e.message || t("jobRequests.declineError")); setShowDecline(false); } finally { setDeclining(false); } };
  return <div className="min-w-0"><PageHeader title={request.requesterName} description={t("jobRequests.detailDescription")} back={{ href: "/jobs/requests", label: t("jobRequests.backToQueue") }} />
    {error && <p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <section className="card space-y-4"><div className="flex flex-wrap items-center gap-2"><span className={`badge ${request.status === "declined" ? "bg-red-100 text-red-700" : request.status === "action_required" ? "bg-amber-100 text-amber-800" : "bg-green-100 text-green-700"}`}>{t(`jobRequests.statuses.${request.status}`)}</span><span className="badge bg-primary-50 text-primary-800">{t("jobRequests.authenticatedSource")}</span></div><div className="grid gap-3 text-sm sm:grid-cols-2"><p className="flex items-start gap-2"><User className="h-4 w-4 shrink-0 text-gray-400"/><span className="break-words">{request.relationshipName || request.requesterName}</span></p><p className="flex items-start gap-2"><MapPin className="h-4 w-4 shrink-0 text-gray-400"/><span className="break-words">{[request.locationName, request.locationAddress].filter(Boolean).join(" · ")}</span></p><p className="flex items-start gap-2"><Sparkles className="h-4 w-4 shrink-0 text-gray-400"/>{request.requestedService}</p><p className="text-gray-500">{t("jobRequests.submitted", { date: new Date(request.submittedAt).toLocaleString() })}</p></div>{request.requestedAddOns.length > 0 && <div><h2 className="text-sm font-semibold">{t("jobRequests.addOns")}</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-gray-700">{request.requestedAddOns.map((item: any) => <li key={item.sourceCompanyAddOnId}>{item.name}{item.quantity ? ` × ${item.quantity}` : ""}</li>)}</ul></div>}{request.notes && <div><h2 className="text-sm font-semibold">{t("jobRequests.clientNotes")}</h2><p className="mt-1 whitespace-pre-wrap break-words text-sm text-gray-700">{request.notes}</p></div>}</section>
    <section className="card mt-4"><h2 className="flex items-center gap-2 font-semibold"><Calendar className="h-4 w-4"/>{t("jobRequests.preferredSchedule")}</h2><p className="mt-3 text-sm">{request.requestedDate || "—"} · {t(`clientRequests.timeWindows.${request.timeWindow}`, { defaultValue: request.timeWindow })}</p><p className="mt-2 text-sm text-amber-700">{t("jobRequests.preferenceNotice")}</p></section>
    {request.status === "declined" ? <section className="card mt-4 border-red-200"><h2 className="font-semibold text-red-800">{t("jobRequests.statuses.declined")}</h2>{request.clientFacingDecisionNote && <p className="mt-2 whitespace-pre-wrap break-words text-sm text-gray-700">{request.clientFacingDecisionNote}</p>}</section> : request.linkedJob ? <section className="card mt-4"><h2 className="font-semibold">{t("jobRequests.finalSchedule")}</h2><p className="mt-2 text-sm">{request.linkedJob.scheduledDate} · {request.linkedJob.startTime || "—"}</p><Link href={`/jobs/${request.linkedJob._id}`} className="mt-3 inline-block font-medium text-primary-700">{t("jobRequests.viewJob")}</Link></section> : <><RequestScheduleConfirmation request={request}/><button type="button" onClick={() => setShowDecline(true)} className="btn-danger mt-4 flex w-full items-center justify-center gap-2 sm:w-auto"><XCircle className="h-4 w-4"/>{t("jobRequests.decline")}</button></>}
    <details className="card mt-4"><summary className="cursor-pointer font-semibold text-primary-700 focus:outline-none focus:ring-2 focus:ring-primary-500">{t("jobRequests.advancedTools")}</summary><p className="mt-2 text-sm text-gray-600">{t("jobRequests.advancedDescription")}</p><Link href={`/requests/${request._id}?advanced=1`} className="mt-3 inline-block font-medium text-primary-700">{t("jobRequests.openAdvanced")}</Link></details>
    {showDecline && <div className="card mt-4 border-red-200"><label className="text-sm font-medium">{t("jobRequests.clientExplanation")}<textarea maxLength={500} rows={3} className="input-field mt-1" value={note} onChange={e => setNote(e.target.value)}/></label><p className="mt-1 text-xs text-gray-500">{t("jobRequests.clientExplanationHelp")}</p><div className="mt-3 flex flex-col-reverse gap-2 sm:flex-row"><button type="button" className="btn-secondary" onClick={() => setShowDecline(false)}>{t("common.cancel")}</button><button type="button" className="btn-danger" onClick={() => setConfirmDecline(true)}>{t("jobRequests.decline")}</button></div></div>}
    <ConfirmDialog open={confirmDecline} onOpenChange={setConfirmDecline} title={t("jobRequests.declineTitle")} description={t("jobRequests.declineConfirm")} confirmLabel={t("jobRequests.declineConfirmAction")} confirmVariant="danger" onConfirm={doDecline} loading={declining}/>
  </div>;
}
