import { useState, type ReactNode } from "react";
import { Link } from "wouter";
import { Banknote, CalendarDays, CheckCircle2, Clock3, UserRound } from "lucide-react";
import { DemoShell } from "../../demo/DemoShell";
import { buildShowcasePath } from "../../demo/showcaseRegistry";
import { brightSideWorkerHomeFixture, brightSideWorkerJobs } from "../../demo/fixtures/workerShowcaseFixtures";

const workerPath = (path: string, presentation: boolean) => buildShowcasePath("worker", path, presentation);
function Frame({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <div className="min-w-0 space-y-6"><header><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary-700">BrightSide Cleaning Co.</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-gray-600">{description}</p></header>{children}</div>; }

export function DemoWorkerOperationsPage({ page, presentation, currentPath }: { page: string; presentation: boolean; currentPath: string }) {
  return <DemoShell presentation={presentation} persona="worker" currentPath={currentPath}>{page === "/calendar" ? <Calendar presentation={presentation} /> : page === "/availability" ? <Availability /> : page === "/payments" ? <Payments /> : <Settings />}</DemoShell>;
}

function Calendar({ presentation }: { presentation: boolean }) { return <Frame title="My calendar" description="Elena’s confirmed BrightSide assignments across the next two service days."><section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="divide-y divide-gray-100">{brightSideWorkerJobs.filter(job=>job.status!=="approved").map(job=><article key={job.id} className="grid gap-3 px-4 py-4 sm:grid-cols-[7rem_minmax(0,1fr)_auto] sm:items-center sm:px-5"><div><p className="font-semibold">{job.dateLabel}</p><p className="text-sm text-gray-500">{job.startTime}</p></div><div className="min-w-0"><Link href={workerPath(`/jobs/${job.id}`,presentation)} className="font-medium text-primary-700">{job.propertyName}</Link><p className="break-words text-sm text-gray-500">{job.serviceTypeLabel} · {job.durationMinutes/60} hr</p></div><span className="badge bg-blue-100 text-blue-800">{job.status.replace(/_/g," ")}</span></article>)}</div></section></Frame>; }
function Availability() { const [selected,setSelected]=useState("Regular schedule"); return <Frame title="Availability" description="A presentation-only view of Elena’s working pattern; selections are local and never saved."><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_18rem]"><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Weekly availability</h2><div className="mt-4 divide-y divide-gray-100">{[["Monday","8:00 AM–4:00 PM"],["Tuesday","8:00 AM–4:00 PM"],["Wednesday","Unavailable"],["Thursday","9:00 AM–5:00 PM"],["Friday","8:00 AM–3:00 PM"]].map(([day,hours])=><div key={day} className="flex justify-between gap-4 py-3 text-sm"><span className="font-medium">{day}</span><span className="text-right text-gray-600">{hours}</span></div>)}</div></section><section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><CalendarDays className="h-5 w-5 text-blue-700"/><h2 className="mt-3 font-semibold">Showcase control</h2><div className="mt-3 grid gap-2">{["Regular schedule","Date exceptions"].map(option=><button key={option} type="button" onClick={()=>setSelected(option)} className={`min-h-11 rounded-lg border px-3 text-left text-sm ${selected===option?"border-primary-500 bg-white text-primary-800":"border-blue-200 bg-blue-50 text-blue-800"}`}>{option}</button>)}</div><p className="mt-3 text-xs text-blue-700">Local preview only. Nothing is submitted.</p></section></div></Frame>; }
function Payments() { const payments=brightSideWorkerHomeFixture.payments; return <Frame title="Payments" description="Planned and completed job pay connected to Elena’s Showcase assignments."><div className="grid gap-4 sm:grid-cols-2">{[["Planned",payments.filter(x=>x.paymentStatus==="PLANNED").reduce((s,x)=>s+x.plannedPayCents,0),Clock3],["Paid",payments.filter(x=>x.paymentStatus==="PAID").reduce((s,x)=>s+x.plannedPayCents,0),CheckCircle2]].map(([label,cents,Icon])=>{const TileIcon=Icon as typeof Clock3;return <div key={String(label)} className="rounded-2xl border border-gray-200 bg-white p-5"><TileIcon className="h-5 w-5 text-primary-600"/><p className="mt-3 text-2xl font-bold">${(Number(cents)/100).toFixed(2)}</p><p className="text-sm text-gray-500">{String(label)}</p></div>})}</div><section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="divide-y divide-gray-100">{payments.map(item=><article key={item.id} className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><p className="font-medium">{item.jobLabel}</p><p className="text-sm text-gray-500">BrightSide job payment</p></div><div className="flex items-center justify-between gap-4 sm:justify-end"><span className="font-semibold">${(item.plannedPayCents/100).toFixed(2)}</span><span className={`badge ${item.paymentStatus==="PAID"?"bg-green-100 text-green-800":"bg-amber-100 text-amber-800"}`}>{item.paymentStatus.toLowerCase()}</span></div></article>)}</div></section><p className="flex items-center gap-2 text-sm text-gray-500"><Banknote className="h-4 w-4"/>No live payout or banking action is available in Showcase.</p></Frame>; }
function Settings() { return <Frame title="Profile & settings" description="Representative worker profile details and onboarding status in a read-only view."><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-5"><UserRound className="h-6 w-6 text-primary-600"/><h2 className="mt-3 text-lg font-semibold">Elena Ruiz</h2><p className="text-sm text-gray-500">Lead cleaner · Blue Ridge Team</p><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-gray-500">Company</dt><dd className="font-medium">BrightSide Cleaning Co.</dd></div><div className="flex justify-between gap-4"><dt className="text-gray-500">Eligibility</dt><dd className="font-medium text-green-700">Eligible</dd></div></dl></section><section className="rounded-2xl border border-gray-200 bg-white p-5"><h2 className="font-semibold">Onboarding</h2><div className="mt-4 rounded-xl bg-amber-50 p-4"><p className="font-medium text-amber-900">1 item needs attention</p><p className="mt-1 text-sm text-amber-800">Review updated safety policy</p></div><p className="mt-4 text-sm text-gray-500">Controls are intentionally omitted because Showcase does not persist changes.</p></section></div></Frame>; }
