import type { ReactNode } from "react";
import { Link } from "wouter";
import { BarChart3, Building2, CalendarDays, CheckCircle2, Clock3, DollarSign, MapPin, Settings2, Sparkles, Users } from "lucide-react";
import { DemoShell } from "../../demo/DemoShell";
import { buildShowcasePath } from "../../demo/showcaseRegistry";
import { brightSideWorkerJobs } from "../../demo/fixtures/workerShowcaseFixtures";
import {
  getShowcaseClient,
  getShowcaseCommercialAccount,
  getShowcaseOwnerRequest,
  getShowcaseProperty,
  getShowcaseWorker,
  showcaseAnalytics,
  showcaseClients,
  showcaseCommercialAccounts,
  showcaseInvoices,
  showcaseOwnerRequests,
  showcaseProperties,
  showcaseSchedule,
  showcaseWorkers,
  showcaseWorkspace,
} from "../../demo/fixtures/operationsShowcaseFixtures";

const ownerPath = (path: string, presentation: boolean) => buildShowcasePath("owner", path, presentation);
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100);

function Frame({ eyebrow = "BrightSide Cleaning Co.", title, description, children }: { eyebrow?: string; title: string; description: string; children: ReactNode }) {
  return <div className="min-w-0 space-y-6"><header><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary-700">{eyebrow}</p><h1 className="mt-2 break-words text-2xl font-bold tracking-tight text-gray-950 sm:text-3xl">{title}</h1><p className="mt-2 max-w-3xl text-sm text-gray-600 sm:text-base">{description}</p></header>{children}</div>;
}
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="min-w-0 overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 px-4 py-4 sm:px-5"><h2 className="font-semibold text-gray-900">{title}</h2></div>{children}</section>; }
function Status({ children, tone = "green" }: { children: ReactNode; tone?: "green" | "blue" | "amber" | "gray" }) { const tones = { green: "bg-green-100 text-green-800", blue: "bg-blue-100 text-blue-800", amber: "bg-amber-100 text-amber-800", gray: "bg-gray-100 text-gray-700" }; return <span className={`badge ${tones[tone]}`}>{children}</span>; }
function DetailLink({ href, presentation, children }: { href: string; presentation: boolean; children: ReactNode }) { return <Link href={ownerPath(href, presentation)} className="font-medium text-primary-700 outline-none hover:text-primary-800 focus-visible:ring-2 focus-visible:ring-primary-500">{children}</Link>; }

export function DemoOwnerOperationsPage({ page, presentation, currentPath }: { page: string; presentation: boolean; currentPath: string }) {
  let content: ReactNode;
  if (page === "/properties") content = <Properties presentation={presentation} />;
  else if (page === "/employees") content = <Team presentation={presentation} />;
  else if (page === "/calendar") content = <Calendar presentation={presentation} />;
  else if (page === "/requests") content = <Requests presentation={presentation} />;
  else if (page === "/clients") content = <Clients presentation={presentation} />;
  else if (page === "/commercial-accounts") content = <Commercial presentation={presentation} />;
  else if (page === "/commercial-invoices" || page === "/financials") content = <Financials />;
  else if (page === "/analytics") content = <Analytics />;
  else content = <Settings />;
  return <DemoShell presentation={presentation} currentPath={currentPath}>{content}</DemoShell>;
}

function Properties({ presentation }: { presentation: boolean }) { return <Frame title="Properties" description="Service locations, access context, and the next scheduled work across BrightSide."><div className="grid gap-4 md:grid-cols-2">{showcaseProperties.map((item) => <article key={item.id} className="min-w-0 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words text-lg font-semibold">{item.name}</h2><p className="mt-1 flex min-w-0 items-start gap-1.5 break-words text-sm text-gray-500"><MapPin className="mt-0.5 h-4 w-4 flex-none" />{item.address}</p></div><Status>{item.type}</Status></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-gray-500">Client</dt><dd className="font-medium">{item.client}</dd></div><div><dt className="text-gray-500">Cadence</dt><dd className="font-medium">{item.cadence}</dd></div><div className="col-span-2"><dt className="text-gray-500">Next service</dt><dd className="font-medium">{item.nextService}</dd></div></dl><div className="mt-5 border-t pt-4"><DetailLink href={`/properties/${item.id}`} presentation={presentation}>View property context →</DetailLink></div></article>)}</div></Frame>; }
function Team({ presentation }: { presentation: boolean }) { return <Frame title="Team" description="The people delivering BrightSide’s residential, rental, and property-care work."><div className="grid gap-4 lg:grid-cols-3">{showcaseWorkers.map((worker) => <article key={worker.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-primary-100 font-bold text-primary-800">{worker.name.split(" ").map(x => x[0]).join("")}</div><div><h2 className="font-semibold">{worker.name}</h2><p className="text-sm text-gray-500">{worker.role}</p></div></div><dl className="mt-5 space-y-2 text-sm"><div className="flex justify-between gap-3"><dt className="text-gray-500">Status</dt><dd><Status tone={worker.status === "On job" ? "blue" : "green"}>{worker.status}</Status></dd></div><div className="flex justify-between gap-3"><dt className="text-gray-500">Team</dt><dd className="font-medium">{worker.team}</dd></div><div className="flex justify-between gap-3"><dt className="text-gray-500">Jobs this week</dt><dd className="font-medium">{worker.jobsThisWeek}</dd></div></dl><div className="mt-5 border-t pt-4"><DetailLink href={`/employees/${worker.id}`} presentation={presentation}>View assignments →</DetailLink></div></article>)}</div></Frame>; }
function Calendar({ presentation }: { presentation: boolean }) { return <Frame title="Calendar" description="A fixture-driven week showing who is going where, for which client, and why."><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_17rem]"><Panel title="August 2–3 schedule"><div className="divide-y divide-gray-100">{showcaseSchedule.map((job) => <article key={job.id} className="grid gap-3 px-4 py-4 sm:grid-cols-[7rem_minmax(0,1fr)_auto] sm:items-center sm:px-5"><div><p className="font-semibold">{job.dateLabel}</p><p className="text-sm text-gray-500">{job.startTime}</p></div><div className="min-w-0"><DetailLink href={`/jobs`} presentation={presentation}>{job.propertyName}</DetailLink><p className="break-words text-sm text-gray-500">{job.client} · {job.worker}</p></div><Status tone={job.status === "in_progress" ? "blue" : "green"}>{job.status.replace(/_/g, " ")}</Status></article>)}</div></Panel><div className="space-y-3">{[["Scheduled jobs","4",CalendarDays],["Assigned","4",Users],["Needs attention","1",Clock3]].map(([label,value,Icon]) => { const TileIcon = Icon as typeof CalendarDays; return <div key={String(label)} className="rounded-2xl border border-gray-200 bg-white p-4"><TileIcon className="h-5 w-5 text-primary-600" /><p className="mt-3 text-2xl font-bold">{String(value)}</p><p className="text-sm text-gray-500">{String(label)}</p></div>; })}</div></div></Frame>; }
function Requests({ presentation }: { presentation: boolean }) { return <Frame title="Requests" description="Incoming client demand moving from review to scheduling and completed service."><Panel title="Service request pipeline"><div className="divide-y divide-gray-100">{showcaseOwnerRequests.map((request) => <article key={request.id} className="grid gap-3 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_9rem_auto] sm:items-center sm:px-5"><div className="min-w-0"><DetailLink href={`/requests/${request.id}`} presentation={presentation}>{request.service}</DetailLink><p className="break-words text-sm text-gray-500">{request.client} · {request.property}</p></div><p className="text-sm text-gray-600">Requested {request.requestedDate}</p><Status tone={request.status === "submitted" ? "amber" : request.status === "scheduled" ? "blue" : "green"}>{request.status}</Status></article>)}</div></Panel></Frame>; }
function Clients({ presentation }: { presentation: boolean }) { return <Frame title="Clients" description="Residential and business relationships connected to locations, requests, and recurring service."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{showcaseClients.map((client) => <article key={client.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{client.name}</h2><p className="text-sm text-gray-500">{client.business}</p></div><Status>{client.status}</Status></div><p className="mt-4 text-sm text-gray-600">{client.services}</p><p className="mt-2 text-sm text-gray-500">{client.locations} connected location{client.locations === 1 ? "" : "s"}</p><div className="mt-5 border-t pt-4"><DetailLink href={`/clients/${client.id}`} presentation={presentation}>View relationship →</DetailLink></div></article>)}</div></Frame>; }
function Commercial({ presentation }: { presentation: boolean }) { return <Frame title="Commercial accounts" description="Recurring service relationships with cadence, location, and billing context."><div className="grid gap-4 lg:grid-cols-2">{showcaseCommercialAccounts.map((account) => <article key={account.id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{account.name}</h2><p className="mt-1 text-sm text-gray-500">{account.location}</p></div><Status>{account.status}</Status></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-gray-500">Service cadence</dt><dd className="font-medium">{account.cadence}</dd></div><div><dt className="text-gray-500">Monthly value</dt><dd className="font-medium">{money(account.monthlyValueCents)}</dd></div><div><dt className="text-gray-500">Next service</dt><dd className="font-medium">{account.nextService}</dd></div><div><dt className="text-gray-500">Contact</dt><dd className="font-medium">{account.contact}</dd></div></dl><div className="mt-5 border-t pt-4"><DetailLink href={`/commercial-accounts/${account.id}`} presentation={presentation}>View account context →</DetailLink></div></article>)}</div></Frame>; }
function Financials() { const total = showcaseInvoices.reduce((sum, item) => sum + item.totalCents, 0); return <Frame title="Financial overview" description="Representative BrightSide invoices only—no live payment processing is connected."><div className="grid gap-4 sm:grid-cols-3">{[["Invoice total",money(total),DollarSign],["Paid",money(showcaseInvoices.filter(x=>x.status==="paid").reduce((s,x)=>s+x.totalCents,0)),CheckCircle2],["Outstanding",money(showcaseInvoices.filter(x=>x.status!=="paid").reduce((s,x)=>s+x.totalCents,0)),Clock3]].map(([label,value,Icon]) => { const TileIcon=Icon as typeof DollarSign; return <div key={String(label)} className="rounded-2xl border border-gray-200 bg-white p-5"><TileIcon className="h-5 w-5 text-primary-600"/><p className="mt-3 text-2xl font-bold">{String(value)}</p><p className="text-sm text-gray-500">{String(label)}</p></div>; })}</div><Panel title="Invoices"><div className="divide-y divide-gray-100">{showcaseInvoices.map(invoice => <article key={invoice._id} className="grid gap-2 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_8rem_7rem_auto] sm:items-center sm:px-5"><div><p className="font-medium">{invoice.title}</p><p className="text-sm text-gray-500">{invoice.invoiceNumber} · {invoice.client}</p></div><p className="text-sm">Due {invoice.dueDate}</p><p className="font-semibold">{money(invoice.totalCents)}</p><Status tone={invoice.status === "paid" ? "green" : "amber"}>{invoice.status}</Status></article>)}</div></Panel></Frame>; }
function Analytics() { const max=Math.max(...showcaseAnalytics.weeklyJobs); return <Frame title="Analytics" description="Operational signals for the fictional BrightSide workspace, not platform-wide claims."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{showcaseAnalytics.metrics.map(([label,value,note]) => <article key={label} className="rounded-2xl border border-gray-200 bg-white p-5"><BarChart3 className="h-5 w-5 text-primary-600"/><p className="mt-4 text-2xl font-bold">{value}</p><h2 className="text-sm font-medium">{label}</h2><p className="mt-2 text-xs text-gray-500">{note}</p></article>)}</div><Panel title="Completed jobs by week"><div className="flex h-52 items-end gap-4 px-5 py-6">{showcaseAnalytics.weeklyJobs.map((value,index)=><div key={index} className="flex flex-1 flex-col items-center gap-2"><span className="text-sm font-semibold">{value}</span><div className="w-full max-w-20 rounded-t-lg bg-primary-500" style={{height:`${Math.round(value/max*130)}px`}}/><span className="text-xs text-gray-500">Week {index+1}</span></div>)}</div></Panel></Frame>; }
function Settings() { return <Frame title="Workspace settings" description="A read-only view of representative BrightSide configuration."><div className="grid gap-4 lg:grid-cols-2"><Panel title="Company profile"><dl className="divide-y divide-gray-100 px-5">{Object.entries({"Company name":showcaseWorkspace.companyName,"Service area":showcaseWorkspace.serviceArea,"Time zone":showcaseWorkspace.timezone}).map(([key,value])=><div key={key} className="grid gap-1 py-4 sm:grid-cols-[10rem_1fr]"><dt className="text-sm text-gray-500">{key}</dt><dd className="font-medium">{value}</dd></div>)}</dl></Panel><Panel title="Operating defaults"><dl className="divide-y divide-gray-100 px-5">{Object.entries({"Default job duration":showcaseWorkspace.defaultDuration,"Notifications":showcaseWorkspace.notifications,"Showcase controls":"Read only"}).map(([key,value])=><div key={key} className="grid gap-1 py-4 sm:grid-cols-[10rem_1fr]"><dt className="text-sm text-gray-500">{key}</dt><dd className="font-medium">{value}</dd></div>)}</dl></Panel></div><div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800"><Settings2 className="mr-2 inline h-4 w-4"/>Changes are intentionally disabled in the Showcase.</div></Frame>; }

export function DemoOwnerDetailPage({ kind, id, presentation, currentPath }: { kind: "property" | "employee" | "request" | "client" | "commercial"; id: string; presentation: boolean; currentPath: string }) {
  const item = kind === "property" ? getShowcaseProperty(id) : kind === "employee" ? getShowcaseWorker(id) : kind === "request" ? getShowcaseOwnerRequest(id) : kind === "client" ? getShowcaseClient(id) : getShowcaseCommercialAccount(id);
  if (!item) return <DemoShell presentation={presentation} currentPath={currentPath}><Frame title="Showcase record not found" description="This record is not part of the BrightSide fixture story."><DetailLink href="/" presentation={presentation}>Return to Owner home</DetailLink></Frame></DemoShell>;
  let content: ReactNode;
  if (kind === "property") { const property=item as ReturnType<typeof getShowcaseProperty> & {}; const job=brightSideWorkerJobs.find(x=>x.id===property.jobId); content=<Frame title={property.name} description={`${property.client} · ${property.type}`}><div className="grid gap-4 lg:grid-cols-2"><Panel title="Location context"><dl className="space-y-4 p-5"><div><dt className="text-sm text-gray-500">Address</dt><dd className="font-medium">{property.address}</dd></div><div><dt className="text-sm text-gray-500">Service cadence</dt><dd className="font-medium">{property.cadence}</dd></div><div><dt className="text-sm text-gray-500">Property notes</dt><dd>{property.notes}</dd></div></dl></Panel><Panel title="Connected job"><div className="p-5"><h2 className="font-semibold">{job?.serviceTypeLabel}</h2><p className="mt-1 text-sm text-gray-600">{job?.dateLabel} · {job?.startTime} · {job && "teamName" in job ? job.teamName : "Assignment pending"}</p><div className="mt-4"><DetailLink href="/jobs" presentation={presentation}>Open job schedule →</DetailLink></div></div></Panel></div></Frame>; }
  else if (kind === "employee") { const worker=item as ReturnType<typeof getShowcaseWorker> & {}; const job=brightSideWorkerJobs.find(x=>x.id===worker.nextJobId); content=<Frame title={worker.name} description={`${worker.role} · ${worker.team}`}><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><Users className="h-5 w-5 text-primary-600"/><p className="mt-3 text-2xl font-bold">{worker.jobsThisWeek}</p><p className="text-sm text-gray-500">Jobs this week</p></div><div className="rounded-2xl border bg-white p-5 sm:col-span-2"><h2 className="font-semibold">Next assignment</h2><p className="mt-3 text-lg font-medium">{job?.propertyName}</p><p className="text-sm text-gray-500">{job?.dateLabel} · {job?.startTime}</p><div className="mt-4"><DetailLink href="/jobs" presentation={presentation}>View job context →</DetailLink></div></div></div></Frame>; }
  else if (kind === "request") { const request=item as ReturnType<typeof getShowcaseOwnerRequest> & {}; content=<Frame title={request.service} description={`${request.client} · ${request.property}`}><div className="grid gap-4 lg:grid-cols-2"><Panel title="Request context"><dl className="space-y-4 p-5"><div><dt className="text-sm text-gray-500">Status</dt><dd className="mt-1"><Status tone={request.status==="submitted"?"amber":"blue"}>{request.status}</Status></dd></div><div><dt className="text-sm text-gray-500">Requested date</dt><dd className="font-medium">{request.requestedDate}</dd></div></dl></Panel><Panel title="Workflow"><div className="p-5"><Sparkles className="h-5 w-5 text-primary-600"/><p className="mt-3 text-sm text-gray-600">Request reviewed → proposal accepted → schedule confirmed → job delivered.</p>{request.scheduledJobId&&<div className="mt-4"><DetailLink href="/jobs" presentation={presentation}>View scheduled work →</DetailLink></div>}</div></Panel></div></Frame>; }
  else if (kind === "client") { const client=item as ReturnType<typeof getShowcaseClient> & {}; content=<Frame title={client.name} description={`${client.business} · ${client.services}`}><div className="grid gap-4 lg:grid-cols-2"><Panel title="Relationship"><div className="p-5"><Status>{client.status}</Status><p className="mt-4 text-sm text-gray-600">{client.locations} connected locations with BrightSide service history.</p><div className="mt-4"><DetailLink href={`/properties/${client.propertyId}`} presentation={presentation}>Open primary location →</DetailLink></div></div></Panel><Panel title="Current journey"><div className="p-5"><p className="text-sm text-gray-600">A client request connects this relationship to a scheduled service.</p><div className="mt-4"><DetailLink href={`/requests/${client.requestId}`} presentation={presentation}>Open request →</DetailLink></div></div></Panel></div></Frame>; }
  else { const account=item as ReturnType<typeof getShowcaseCommercialAccount> & {}; content=<Frame title={account.name} description={`${account.location} · ${account.cadence}`}><div className="grid gap-4 lg:grid-cols-2"><Panel title="Recurring service"><dl className="space-y-4 p-5"><div><dt className="text-sm text-gray-500">Next service</dt><dd className="font-medium">{account.nextService}</dd></div><div><dt className="text-sm text-gray-500">Monthly value</dt><dd className="font-medium">{money(account.monthlyValueCents)}</dd></div></dl></Panel><Panel title="Billing context"><div className="p-5"><Building2 className="h-5 w-5 text-primary-600"/><p className="mt-3 text-sm text-gray-600">The account’s representative invoice is included in the financial Showcase.</p><div className="mt-4"><DetailLink href="/commercial-invoices" presentation={presentation}>Open invoices →</DetailLink></div></div></Panel></div></Frame>; }
  return <DemoShell presentation={presentation} currentPath={currentPath}>{content}</DemoShell>;
}
